name: ESPHome
services:
  ESPHome:
    container_name: ESPHome
    hostname: esphome
    image: ghcr.io/esphome/esphome:2026.4.2@sha256:a2784bc539dcf7529241bfe4425d645f1076031f9bf9ce07f5d59d1c45e9ff22
    restart: unless-stopped
    networks:
      AAA_LAN:
        mac_address: 0A:00:00:00:00:03 # Set static LAN MAC address for container (e.g. MAC address used in `AAA_LAN` MacVLAN network persists between container stops/starts)
      ESPHome:
    volumes:
      - ./config:/config
      - esphome_build:/config/.esphome # Put build directory outside of the project folder
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      # allow read_only fs
      - PLATFORMIO_CORE_DIR=.plattformio
      - PLATFORMIO_GLOBALLIB_DIR=.plattformioLibs

    user: "${UID}:${GID}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald

    deploy:
      resources:
        limits:
          cpus: 5
          memory: 2GB
          pids: 100

networks:
  ESPHome:
    external: true
  AAA_LAN:
    external: true

volumes:
  esphome_build:
