name: ESPHome
services:
  ESPHome:
    container_name: ESPHome
    hostname: esphome
    image: ghcr.io/esphome/esphome:2026.4.5@sha256:7419641c7fd8e37d6362f71c458bb17570f1f471cfea3b022b30dfd8117a2361
    restart: unless-stopped
    networks:
      AAA_LAN:
      ESPHome:
    volumes:
      - ./config:/config
      - esphome_build:/config/.esphome # Put build directory outside of the project folder
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      # allow read_only fs
      - PLATFORMIO_CORE_DIR=.plattformio
      - PLATFORMIO_GLOBALLIB_DIR=.plattformioLibs

    user: "${UID}:${GID}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald

    deploy:
      resources:
        limits:
          cpus: 5
          memory: 2GB
          pids: 100

networks:
  ESPHome:
    external: true
  AAA_LAN:
    external: true

volumes:
  esphome_build:
