name: ESPHome
services:
  ESPHome:
    container_name: ESPHome
    hostname: esphome
    image: ghcr.io/esphome/esphome:2026.6.2@sha256:526a75c8d64a0d962a3b088c3af4fa7cf8ecf7161b995be57fc95b0726496a39
    restart: unless-stopped
    networks:
      ESPHome:
      LAN:
        gw_priority: 1
    volumes:
      - ./config:/config
      - esphome_build:/config/.esphome # Put build directory outside of the project folder
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - ESPHOME_USERNAME=${ESPHOME_USERNAME}
      - ESPHOME_PASSWORD=${ESPHOME_PASSWORD}
      # https://github.com/esphome/issues/issues/3558
      - PLATFORMIO_CORE_DIR=.plattformio
      - PLATFORMIO_GLOBALLIB_DIR=.plattformioLibs

    user: "${UID}:${GID}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald

    deploy:
      resources:
        limits:
          cpus: 5
          memory: 2GB
          pids: 100

networks:
  ESPHome:
    external: true
  LAN:
    external: true

volumes:
  esphome_build:
